import type { CatalogItem, DesignResourceCategory, DesignResourceType } from './types';
import {
  VpcIcon,
  SubnetIcon,
  IgwIcon,
  NatIcon,
  RouteTableIcon,
  Ec2Icon,
  LambdaIcon,
  EcsIcon,
  RdsIcon,
  DynamodbIcon,
  LbIcon,
  TargetGroupIcon,
  SecurityGroupIcon,
  IamRoleIcon,
  S3Icon,
} from '@/components/nodes/icons/AwsIcons';

export const CATEGORY_LABELS: Record<DesignResourceCategory, { label: string; iconColor: string }> = {
  networking: { label: 'Networking & Content Delivery', iconColor: '#1B660F' },
  compute: { label: 'Compute', iconColor: '#ED7100' },
  database: { label: 'Database', iconColor: '#3B48CC' },
  load_balancing: { label: 'Load Balancing', iconColor: '#8C4FFF' },
  security: { label: 'Security, Identity & Compliance', iconColor: '#DD344C' },
  storage: { label: 'Storage', iconColor: '#3F8624' },
};

export const AWS_CATALOG: CatalogItem[] = [
  // ── Networking ──
  {
    type: 'vpc',
    name: 'VPC',
    awsServiceName: 'Amazon Virtual Private Cloud',
    category: 'networking',
    description: 'Logically isolated virtual network for your AWS cloud resources.',
    color: '#1B660F',
    icon: VpcIcon,
    isContainer: true,
    defaultConfig: {
      cidrBlock: '10.0.0.0/16',
      enableDnsHostnames: true,
      enableDnsSupport: true,
    },
    explanation: {
      title: 'Virtual Private Cloud (VPC)',
      summary: 'A VPC is your private data center in the cloud.',
      why: 'It gives you complete control over your virtual networking environment, including selection of IP address ranges, creation of subnets, and configuration of route tables.',
      bestPractice: 'Use a standard /16 CIDR block (e.g. 10.0.0.0/16) so you have ample space to carve out public and private subnets across multiple availability zones.',
    },
  },
  {
    type: 'public_subnet',
    name: 'Public Subnet',
    awsServiceName: 'VPC Public Subnet',
    category: 'networking',
    description: 'Subnet with direct route to Internet Gateway for public-facing resources.',
    color: '#147EBA',
    icon: SubnetIcon,
    isContainer: true,
    defaultConfig: {
      cidrBlock: '10.0.1.0/24',
      availabilityZone: 'us-east-1a',
      mapPublicIpOnLaunch: true,
      subnetType: 'public',
    },
    explanation: {
      title: 'Public Subnet',
      summary: 'A subnet that has a route table entry pointing to an Internet Gateway.',
      why: 'Public subnets are used strictly for internet-facing ingress components like Application Load Balancers, Bastion hosts, or NAT Gateways.',
      bestPractice: 'Never place databases or critical backend application servers directly in a public subnet. Always front them with load balancers.',
    },
  },
  {
    type: 'private_subnet',
    name: 'Private Subnet',
    awsServiceName: 'VPC Private Subnet',
    category: 'networking',
    description: 'Isolated subnet without direct internet route for backend servers & databases.',
    color: '#0D6494',
    icon: SubnetIcon,
    isContainer: true,
    defaultConfig: {
      cidrBlock: '10.0.2.0/24',
      availabilityZone: 'us-east-1a',
      mapPublicIpOnLaunch: false,
      subnetType: 'private',
    },
    explanation: {
      title: 'Private Subnet',
      summary: 'A subnet with no direct route to the Internet Gateway.',
      why: 'Traffic cannot reach private subnets directly from the outside internet. Servers here can only receive traffic routed through an ALB or NAT Gateway.',
      bestPractice: 'Place all application workloads, microservices, and databases in private subnets for defense-in-depth protection.',
    },
  },
  {
    type: 'internet_gateway',
    name: 'Internet Gateway',
    awsServiceName: 'VPC Internet Gateway (IGW)',
    category: 'networking',
    description: 'VPC component allowing communication between VPC and the internet.',
    color: '#8C4FFF',
    icon: IgwIcon,
    defaultConfig: {},
    explanation: {
      title: 'Internet Gateway (IGW)',
      summary: 'A horizontally scaled, redundant VPC component that enables internet access.',
      why: 'It performs network address translation (NAT) for instances that have public IPv4 addresses and connects your VPC to the public internet.',
      bestPractice: 'Attach exactly one Internet Gateway per VPC. Route public subnets to this gateway via the route table.',
    },
  },
  {
    type: 'nat_gateway',
    name: 'NAT Gateway',
    awsServiceName: 'AWS Managed NAT Gateway',
    category: 'networking',
    description: 'Enables private subnet instances to access the internet while blocking incoming traffic.',
    color: '#8C4FFF',
    icon: NatIcon,
    defaultConfig: {
      connectivityType: 'public',
    },
    explanation: {
      title: 'NAT Gateway',
      summary: 'Network Address Translation service for private subnet egress.',
      why: 'Enables instances in a private subnet to connect to external services (like downloading OS security patches or calling external APIs) without exposing them to incoming internet connections.',
      bestPractice: 'Always place NAT Gateways in a public subnet, and route private subnet traffic through them via route tables.',
    },
  },
  {
    type: 'route_table',
    name: 'Route Table',
    awsServiceName: 'VPC Route Table',
    category: 'networking',
    description: 'Rules determining where network traffic from subnets or gateways is directed.',
    color: '#8C4FFF',
    icon: RouteTableIcon,
    defaultConfig: {
      routes: [{ destination: '10.0.0.0/16', target: 'local' }],
    },
    explanation: {
      title: 'Route Table',
      summary: 'Contains a set of rules (routes) that determine where network traffic is directed.',
      why: 'Each subnet in your VPC must be associated with a route table. This controls whether subnets route to the Internet Gateway, NAT Gateway, or stay local.',
      bestPractice: 'Keep separate route tables for public subnets (routing 0.0.0.0/0 to IGW) and private subnets (routing 0.0.0.0/0 to NAT Gateway).',
    },
  },

  // ── Compute ──
  {
    type: 'ec2',
    name: 'EC2 Instance',
    awsServiceName: 'Amazon Elastic Compute Cloud',
    category: 'compute',
    description: 'Scalable virtual server in the cloud for hosting applications.',
    color: '#ED7100',
    icon: Ec2Icon,
    defaultConfig: {
      instanceType: 't3.micro',
      ami: 'Amazon Linux 2023',
      publicIp: false,
      purpose: 'Backend API',
      securityGroup: '',
      subnet: '',
    },
    explanation: {
      title: 'Amazon EC2 Instance',
      summary: 'A virtual server in AWS to run software applications, APIs, or workers.',
      why: 'EC2 provides scalable computing capacity so you can build and run applications without hardware upfront.',
      bestPractice: 'Because this EC2 is configured as a backend service, place it in a private subnet and route inbound traffic through an Application Load Balancer (ALB).',
    },
  },
  {
    type: 'lambda',
    name: 'Lambda Function',
    awsServiceName: 'AWS Lambda',
    category: 'compute',
    description: 'Serverless compute service that runs code in response to events.',
    color: '#ED7100',
    icon: LambdaIcon,
    defaultConfig: {
      runtime: 'nodejs20.x',
      memorySize: 256,
      timeout: 30,
      handler: 'index.handler',
      iamRole: '',
    },
    explanation: {
      title: 'AWS Lambda',
      summary: 'Event-driven, serverless computing without managing servers.',
      why: 'Run code only when triggered by HTTP requests, database changes, or queue messages. You pay only for compute time consumed.',
      bestPractice: 'Assign a dedicated IAM execution role following the principle of least privilege. Use environment variables for configuration.',
    },
  },
  {
    type: 'ecs',
    name: 'ECS Cluster',
    awsServiceName: 'Amazon Elastic Container Service',
    category: 'compute',
    description: 'Fully managed container orchestration service for Docker containers.',
    color: '#ED7100',
    icon: EcsIcon,
    defaultConfig: {
      launchType: 'FARGATE',
      desiredCount: 2,
      taskMemory: '512',
      taskCpu: '256',
    },
    explanation: {
      title: 'Amazon ECS (Fargate)',
      summary: 'Run and scale containerized applications without provisioning servers.',
      why: 'AWS Fargate handles server management, patching, and scaling for your Docker containers automatically.',
      bestPractice: 'Distribute tasks across at least 2 availability zones in private subnets behind an Application Load Balancer for high availability.',
    },
  },

  // ── Database ──
  {
    type: 'rds',
    name: 'RDS Database',
    awsServiceName: 'Amazon Relational Database Service',
    category: 'database',
    description: 'Managed relational database (PostgreSQL, MySQL, Aurora, etc.).',
    color: '#3B48CC',
    icon: RdsIcon,
    defaultConfig: {
      engine: 'PostgreSQL',
      engineVersion: '16.2',
      instanceClass: 'db.t3.micro',
      allocatedStorage: 20,
      multiAz: false,
      publiclyAccessible: false,
      databaseName: 'appdb',
      port: 5432,
      securityGroup: '',
      subnet: '',
    },
    explanation: {
      title: 'Amazon RDS',
      summary: 'Managed relational database service for structured data.',
      why: 'Automates time-consuming tasks such as provisioning, patching, backup, recovery, and failure detection.',
      bestPractice: 'Never expose RDS directly to the internet (set Publicly Accessible = false). Place in private DB subnets and restrict security groups only to your application servers.',
    },
  },
  {
    type: 'dynamodb',
    name: 'DynamoDB Table',
    awsServiceName: 'Amazon DynamoDB',
    category: 'database',
    description: 'Fast, serverless, key-value NoSQL database designed for any scale.',
    color: '#3B48CC',
    icon: DynamodbIcon,
    defaultConfig: {
      billingMode: 'PAY_PER_REQUEST',
      hashKey: 'id',
      hashKeyType: 'String',
      encryption: 'AWS_MANAGED',
    },
    explanation: {
      title: 'Amazon DynamoDB',
      summary: 'Fully managed serverless NoSQL database offering single-digit millisecond latency.',
      why: 'Seamlessly handles massive scale with zero server administration, automated backups, and built-in caching.',
      bestPractice: 'Use on-demand billing mode (PAY_PER_REQUEST) for unpredictable workloads. Access via IAM roles rather than permanent credentials.',
    },
  },

  // ── Load Balancing ──
  {
    type: 'alb',
    name: 'Application Load Balancer',
    awsServiceName: 'Elastic Load Balancing (ALB)',
    category: 'load_balancing',
    description: 'Distributes incoming HTTP/HTTPS traffic across multiple targets.',
    color: '#8C4FFF',
    icon: LbIcon,
    defaultConfig: {
      scheme: 'internet-facing',
      ipAddressType: 'ipv4',
      protocol: 'HTTP',
      port: 80,
      securityGroup: '',
      subnets: [],
    },
    explanation: {
      title: 'Application Load Balancer (ALB)',
      summary: 'Operates at the request level (layer 7) to route web traffic to backend targets.',
      why: 'Terminates SSL/TLS, balances load across multiple servers, performs health checks, and allows backend instances to remain in secure private subnets.',
      bestPractice: 'Place ALBs in public subnets across at least 2 availability zones. Route traffic to Target Groups pointing to private compute instances.',
    },
  },
  {
    type: 'target_group',
    name: 'Target Group',
    awsServiceName: 'ELB Target Group',
    category: 'load_balancing',
    description: 'Routes requests to registered targets (EC2 instances or ECS tasks).',
    color: '#8C4FFF',
    icon: TargetGroupIcon,
    defaultConfig: {
      protocol: 'HTTP',
      port: 80,
      targetType: 'instance',
      healthCheckPath: '/health',
    },
    explanation: {
      title: 'Target Group',
      summary: 'A logical pool of compute resources (EC2, ECS, or Lambda) monitored by a load balancer.',
      why: 'The load balancer continually runs health checks against targets in this group and routes incoming requests only to healthy instances.',
      bestPractice: 'Configure a lightweight health check endpoint like /health to quickly detect and bypass failing instances.',
    },
  },

  // ── Security ──
  {
    type: 'security_group',
    name: 'Security Group',
    awsServiceName: 'Amazon EC2 Security Group',
    category: 'security',
    description: 'Virtual firewall controlling inbound and outbound traffic at instance level.',
    color: '#DD344C',
    icon: SecurityGroupIcon,
    defaultConfig: {
      description: 'Default application firewall rules',
      rules: [
        {
          id: 'rule-1',
          type: 'inbound',
          protocol: 'tcp',
          portRange: '80',
          source: '0.0.0.0/0',
          description: 'HTTP web traffic',
        },
        {
          id: 'rule-2',
          type: 'inbound',
          protocol: 'tcp',
          portRange: '443',
          source: '0.0.0.0/0',
          description: 'HTTPS secure traffic',
        },
      ],
    },
    explanation: {
      title: 'Security Group',
      summary: 'Stateful virtual firewall for your cloud resources.',
      why: 'Filters all inbound and outbound traffic at the network interface level. Security group rules are deny-all by default until explicit allow rules are added.',
      bestPractice: 'Reference other security groups as sources instead of CIDR IP ranges (e.g. backend servers should only accept traffic from the ALB security group).',
    },
  },
  {
    type: 'iam_role',
    name: 'IAM Role',
    awsServiceName: 'AWS Identity and Access Management (IAM)',
    category: 'security',
    description: 'Identity with specific permissions that AWS services can assume.',
    color: '#DD344C',
    icon: IamRoleIcon,
    defaultConfig: {
      trustedService: 'ec2.amazonaws.com',
      policies: ['AmazonS3ReadOnlyAccess'],
    },
    explanation: {
      title: 'IAM Role',
      summary: 'An AWS identity with specific permissions, assumed by AWS services rather than people.',
      why: 'Allows EC2 instances, Lambda functions, or ECS tasks to access other AWS services (like S3 or DynamoDB) securely without hardcoding static API access keys in code.',
      bestPractice: 'Apply the principle of least privilege: grant only the exact permissions needed for the resource to execute its tasks.',
    },
  },

  // ── Storage ──
  {
    type: 's3',
    name: 'S3 Bucket',
    awsServiceName: 'Amazon Simple Storage Service',
    category: 'storage',
    description: 'Object storage built to retrieve any amount of data from anywhere.',
    color: '#3F8624',
    icon: S3Icon,
    defaultConfig: {
      versioning: true,
      encryption: 'AES256',
      blockPublicAccess: true,
    },
    explanation: {
      title: 'Amazon S3 Bucket',
      summary: 'Highly scalable, 99.999999999% durable cloud object storage.',
      why: 'Store and retrieve static files, images, documents, application backups, and assets with industry-leading security and performance.',
      bestPractice: 'Always keep "Block all public access" ENABLED unless the bucket is specifically hosting public web assets. Enable default AES256 server-side encryption.',
    },
  },
];

export const CATALOG_BY_TYPE = new Map<DesignResourceType, CatalogItem>(
  AWS_CATALOG.map((item) => [item.type, item]),
);
